### ISSUE TITLE
which data should i preparation？

### ISSUE THREAD

**Issue by jisnoalia** [yunguan-wang/SPROD#28]
Thanks for your software. I have some questions about the data. 
1. For gene expression data , Need to provide the count data or normalized data.？
2. For Spot metadata， should I use the row/col  or imagerow/imagecol in seurat@images$coordinates like that?

![image-20220808103052926](http://cos02.mugpeng.top/img202208081031032.png)

Looking forward to your quick reply.Thank u!

**Comment by yunguan-wang** [comment]
Hi @jisnoalia,
Thanks for your questions.
You can use either raw count of normalized data, since the graph building process is not dependent on it. For best performance, I usually use CPM as count input.
For Spot metadata, you should use `imagerow` and `imagecol` as `x` and `Y`.

**Comment by jisnoalia** [comment]
Thanks for your answer. This is very helpful for me.
