### ISSUE TITLE
Sprod can't work on my server

### ISSUE THREAD

**Issue by Life-is-code** [yunguan-wang/SPROD#32]

**Comment by Life-is-code** [comment]
Hello, i'm very interested about your **Sprod imputataion tech**.But when i tried to use it to impute my data about mouse brain.
i have faced some difficulties.
i have tried Sprod to impute my Mousebrain anndata information with X and spatial , i tried to transfer my **adata.**X to be your **Count.txt** and transfer my **adata.obsm['spatial']** to be your **Spot_metadata.csv.** after finished , Sprod running and can't work when running at **denoised.R** stage. First, it stoped at **complete.cases(p_n_n)**:
![image](https://user-images.githubusercontent.com/101504128/188296393-319ff63f-8900-4c08-93c9-5ab96a822c92.png)

because i have no experience about using Rscript ,so i try to **fixed it by '#' , i have annotation two parts in denoised.R** 
![image](https://user-images.githubusercontent.com/101504128/188296452-fae7c715-4c50-4454-8f04-a37ed7b17426.png)

after doing this, i find that I stopped at next stage. 
![image](https://user-images.githubusercontent.com/101504128/188296491-6aeac436-3cd9-4383-8e01-0f13ae50e62d.png)
sprod_log.txt becames below
![image](https://user-images.githubusercontent.com/101504128/188296508-527ebbc4-64a4-4206-a9ee-d3b9b57cff88.png)

so I don't know it's **long vector which i can't support** ? or just **my server can't allocate memory**?or **even worse, both of them**.

**Comment by wtwt5237** [comment]
Hi @Life-is-code , 

Thanks for your interest in our work! It is unclear from these error messages what the problem is. We haven't seen anything like this before. But my guess is that your server cannot allocate enough memory? Maybe try out split-and-stich mode, which will have much lower memory requirement?

Thanks!

Tao

**Comment by Life-is-code** [comment]
OK
i'll tried what you say and try to allocate more memory about this. thankyou!

**Comment by wtwt5237** [comment]
Hi @Life-is-code 

looks like the data is still too large, and L-BFGS-B failed in the core step of the model. split into even smaller pieces?

Thanks!

Tao
