### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by trickovicmatija** [yunguan-wang/SPROD#33]
Hello,
Thanks for the interesting tool! I have some problem with preparing data for SPROD:

My idea is to use the output of space ranger ("outs") to run the data_preprocessing.py in order to prepare the input for the actual SPROD. I am encountering some problems:
1) The script expects that the filtered_feature_bc_matrix is zipped, which is not in the output of space ranger. It's not a big problem, but maybe you can change that so the script is compatible with the default output of space ranger. This is also the case with spatial dir within outs.
2) The bigger problem is that the script asks for the .tif image file, which is also not put in the outs dir. 

I am not very comfortable with image data, so maybe I am asking a naive question. For the space ranger itself, I have used .jpg files. Should I only convert them to .tif and try with that? Or I need to export the picture of a tissue in .tif format to begin with?
Nevertheless, for one of the samples I had .tiff file, so I continued to run data_preprocessing.py with
```
python ~/SPROD/sprod/data_preprocessing.py --input "visium" -v Cax/ -o sprod_output
```
but I get an error:
```
x filtered_feature_bc_matrix/
x filtered_feature_bc_matrix/features.tsv.gz
x filtered_feature_bc_matrix/barcodes.tsv.gz
x filtered_feature_bc_matrix/matrix.mtx.gz
x spatial/
x spatial/tissue_hires_image.png
x spatial/detected_tissue_image.jpg
x spatial/tissue_positions_list.csv
x spatial/aligned_fiducials.jpg
x spatial/scalefactors_json.json
x spatial/tissue_lowres_image.png
cp: Cax/10x_Cax.tiff: No such file or directory
Traceback (most recent call last):
  File "/Users/trickovi/SPROD/sprod/data_preprocessing.py", line 127, in <module>
    data_preprocessing(input_type, output_path)
  File "/Users/trickovi/SPROD/sprod/data_preprocessing.py", line 112, in data_preprocessing
    cts.to_csv(os.path.join(output_path,'Counts.txt'),sep='\t')
  File "/opt/anaconda3/envs/sprod/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/opt/anaconda3/envs/sprod/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/opt/anaconda3/envs/sprod/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/opt/anaconda3/envs/sprod/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'sprod_output/Counts.txt'
```

It seems that it recognised the name of the .tiff file correctly, but reports it as missing. In the Cax dir, I have:
1) 10x_Cax.tiff
2) filtered_feature_bc_matrix.gz
3) spatial.tar.gz
I wonder do you know what could cause this? 

Thanks,
Matija

**Comment by yunguan-wang** [comment]
Hi Matija,
Thanks for you suggestions and interest in Sprod.

For your first suggestion. We developed sprod to be as general as possible and thus we designed the input as the more generic formats available in every ST data, i.e., an expression matrix and a metadata matrix. Thus we did not include scripts to handle outputs from a specific platform. 
For your specific issue, I believe 10x provided codes snippets in R/Python to process the output into an expression matrix format.

For your second question. We are aware that some of the platforms do not provide a matching image, and even for visium, the hi-resolution at 10X level is also not provided by default. 
In your specific user case, you can use the pseudo-image mode instead.

Thanks,
Yunguan
