### ISSUE TITLE
fail to run the demo

### ISSUE THREAD

**Issue by ZDDWLIG** [yunguan-wang/SPROD#37]
Thank you for your great job.I had a problem running the example.The single mode and single pseudoimage mode can run successfully,but the batch mode fail.Do you have any suggestions？

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/88024901/209471249-80a9a13a-1493-47db-b8f0-e85d77648cac.png">

**Comment by wtwt5237** [comment]
hi @ZDDWLIG ,

could you please be more specific? What error message you see in batch mode?

Thanks!

Tao

**Comment by yunguan-wang** [comment]
Hi @ZDDWLIG ,
Thanks for your comment. There was a bug in the test and it was fixed. The test should work now.
