### ISSUE TITLE
Parameter setting

### ISSUE THREAD

**Issue by EddieLv** [yunguan-wang/SPROD#39]
Thanks for your excellent work!
I tested some samples with pseudo-image mode, and found a warning occurring freaquently!
which is:
Warning message:
Lambda may be set too small! 

So I wonder if we need to adjust the Lambda?

**Comment by wtwt5237** [comment]
Hi @EddieLv 

Yes, it will be best if you can do that. You can adjust these tuning parameters and see whether there is any improvement in the diagnostic plots generated by sprod. Please refer to the sup file of our paper for some discussions on the diagnostic plots

Thanks!

Tao
